#!/bin/sh
# **************************************************************************
#              BEGIN of SCRIPT
# **************************************************************************

TMP=`mktemp -d`
CURRENT_DIR=`pwd`
ARCH_NAME=`basename $CURRENT_DIR`
DIR_NUTYX_NAME=`dirname $CURRENT_DIR`
NUTYX_NAME=`basename $DIR_NUTYX_NAME`

[ -f index.html ] && rm index.html

CLASS="even"
IFS="
"
for COLLECTION in *
do
        echo "cd ${CURRENT_DIR}/$COLLECTION"
        cd ${CURRENT_DIR}/$COLLECTION
        [ ! -f .PKGREPO ] && ( cd .. ; continue )
        for LINE in `cat .PKGREPO`
        do
                INFO="`echo $LINE| cut -d "#" -f1 --compl`"
                echo "$COLLECTION#$INFO" >> $TMP/PackagesList
        done
done

cd ${CURRENT_DIR}
[ ! -f $TMP/PackagesList ] && exit
NUMBER=`cat  $TMP/PackagesList|wc -l`

cat > $TMP/index.html << "EOF"
<!DOCTYPE html>
 <html>
  <head>
   <meta charset="utf-8" />
      <link rel="shortcut icon" href="../../favicon.ico">
      <link rel="stylesheet" href="http://www.nutyx.org/css/nutyx.css" />
EOF
echo "      <title>Paquets NuTyX $NUTYX_NAME $ARCH_NAME</title>" >> $TMP/index.html
cat >> $TMP/index.html << "EOF"
  </head>
  <body>
     <table>
      <tr>
        <td width="30%">
              <a href=".."><img id="logo" src="http://www.nutyx.org/graphics/logo_nutyx_120.png" alt="logo nutyx" /></a>
        </td>
        <td>
         <nav>
          <ul>
            <li><a href=".">Accueil</a></li>
            <li><a href="news.html">Nouvelles</a></li>
            <li><a href="information.html">Information</a></li>
            <li><a href="documentation.html">Documentation</a></li>
            <li><a href="installation.html">Installation</a></li>
            <li><a href="faq.html">FAQ</a></li>
            <li><a href="http://forum.nutyx.org/index.php?action=recent">Forum</a></li>
            <li><a href="http://github.com/NuTyX">Code</a></li>
          </ul>
         </nav>
        </td>
       </tr>
      </table>
   <hr>
EOF

echo "
   <h1>Paquets NuTyX $NUTYX_NAME $ARCH_NAME</h1>
    <h2>Nombre de binaires de base: $NUMBER</h2>">> $TMP/index.html

cat >> $TMP/index.html << "EOF"
    <table width="25%" cellspacing="0">
     <tr class="header">
      <td><input id="searchInput" placeholder="Search for ... "></td>
     </tr>
    </table>
     <hr>
    <table width="100%" cellspacing="0">
      <tr class="header">
       <td width="5%">COLLECTION</td>
       <td width="10%">NAME</td>
       <td width="5%">VERSION</td>
       <td width="65%">DESCRIPTION</td>
       <td width="5%">DATE</td>
      </tr>
      <tbody id="fbody">
EOF

sort -r $TMP/PackagesList >> $TMP/PackagesList_sorted

for PACKAGE in `cat $TMP/PackagesList_sorted`
do
	collection=`echo $PACKAGE|cut -d "#" -f1`
	DATE=`echo $PACKAGE|cut -d "#" -f2`
	name=`echo $PACKAGE|cut -d "#" -f3`
	version=`echo $PACKAGE|cut -d "#" -f4`
	release=`echo $PACKAGE|cut -d "#" -f5`
	description=`echo $PACKAGE|cut -d "#" -f6`
	url=`echo $PACKAGE|cut -d "#" -f7`
        if [ "$CLASS" == "even" ]; then
                CLASS="odd"
        else
                CLASS="even"
        fi
	build=`date --date=@$DATE +%d-%b-%Y\ %H:%M`
	echo "
        <tr class=\"$CLASS\">
         <td width="5%">$collection</td>
         <td width="10%"><a href=\"${url}\">${name}</a></td>
         <td width="5%"><a href=\"http://downloads.nutyx.org/${NUTYX_NAME}/${ARCH_NAME}/${collection}/${name}/Pkgfile\">$version-$release</a></td>
         <td width="70%">$description</td>
         <td width="10%">$build</td>
        </tr>" >> $TMP/index.html
done
cat >> $TMP/index.html << "EOF"
     </tbody>
    </table>
EOF
NUMBER=`cat  $TMP/PackagesList|wc -l`
echo "<h2>Nombre de binaires de base: $NUMBER</h2>" >> $TMP/index.html
cat >> $TMP/index.html << "EOF"
   <hr>
EOF
DATE=`date +%Y-%m-%d\ %H:%M`
echo "   <p class="updated">Last update on $DATE" >> $TMP/index.html
cat >> $TMP/index.html << "EOF"
   </p>
      <footer>
        <p id="foot">... <img src="http://www.nutyx.org/graphics/logo_nutyx_25.png" alt="nutyx petit logo"> ...<br />
        &copy; 2007 - 2015 <a href="http://nutyx.org">NuTyX</a><br /><br />
      <a href="http://www.wtfpl.net/"><img
         src="http://www.wtfpl.net/wp-content/uploads/2012/12/wtfpl-badge-4.png"
         width="80" height="15" alt="WTFPL" /></a></p>
    </footer>
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
     <script>
      jQuery(function() {
        jQuery("#searchInput").keyup(function() {
          var rows = jQuery("#fbody").find("tr").hide();
          var data = this.value.split(" ");
          jQuery.each(data, function(i, v) {
             v = v.toLowerCase();
             rows.filter(function() {
                return (this.textContent || this.innerText || this.text() || "").toLowerCase().indexOf(v) >= 0;
             })
             .show();
          });
        });
       });
     </script>
 </body>
</html>
EOF
mv $TMP/index.html .
rm -r $TMP
# ********************************************************************
#                     END of SCRIPT
# ********************************************************************
