#!/bin/sh
########################################################################
# Begin sysklogd
#
# Description : Sysklogd loader
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
#               DJ Lucas - dj@linuxfromscratch.org
# Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            $syslog
# Required-Start:      localnet
# Should-Start:
# Required-Stop:       $local_fs sendsignals
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts kernel and system log daemons.
# Description:         Starts kernel and system log daemons.
#                      /etc/fstab.
# X-LFS-Provided-By:   LFS
### END INIT INFO

# Note: sysklogd is not started in runlevel 2 due to possible
# remote logging configurations

. /lib/lsb/init-functions

case "${1}" in
	start)
		do_start_sysklogd
		;;
	stop)
		do_stop_sysklogd
		;;
	reload)
		reload_syslogs
		;;
	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		do_status_sysklogd
		;;
	cleanup)
		do_cleanup_syslogs
		;;

   *)
      echo "Usage: ${0} {start|stop|reload|restart|status|cleanup}"
      exit 1
      ;;
esac

exit 0

# End sysklogd
