#!/bin/bash
if [ ! "$1" -a ! "$2" ]; then
  echo "Usage: $0 output.schemas [--domain gettextdomain] file1.schemas [file2.schemas [...]]"
  exit 1
fi

OUTFILE="$1"
DOMAIN=""
shift

if [ "$1" = "--domain" ]; then
  shift
  DOMAIN=$1
  shift
fi

echo '' > "$OUTFILE"
echo '' >> "$OUTFILE"

while [ "$1" ]; do
  if [ -f "$1" ]; then
    sed -e '/||g' \
	-e 's|||g' \
        -e 's|||g' \
	-e 's|||g' "$1" >> "$OUTFILE"
  fi
  shift
done
  
echo '' >> "$OUTFILE"
if [ "$DOMAIN" != "" ]; then
  sed -ri "s/^([[:space:]]*)()/\1$DOMAIN<\/gettext_domain>\n\1\2/; /^[[:space:]]*[[:space:]]*\$/ d; /^$/d; s/<\/schema>$/&\n/" "$OUTFILE"
fi
