name: tg notify
on: 
  push:
    branches: [testing]

jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message when push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message:  |
             packages-x86_64 on testing: ${{ github.event.commits[0].message }}.
      
